"""add role column to admins

Revision ID: 41a4cf4122fb
Revises: e71acc7e2f5a
Create Date: 2026-06-21 08:29:26.245140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a4cf4122fb'
down_revision: Union[str, Sequence[str], None] = 'e71acc7e2f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('admins', sa.Column('role', sa.String(length=50), nullable=True))
    op.execute("UPDATE admins SET role = 'admin' WHERE role IS NULL")
    op.alter_column('admins', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'role')
    # ### end Alembic commands ###
