"""add error_log to test_variants

Revision ID: 748d437ccb74
Revises: ebe712db9259
Create Date: 2026-06-21 16:58:52.207142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748d437ccb74'
down_revision: Union[str, Sequence[str], None] = 'ebe712db9259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_variants', sa.Column('error_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_variants', 'error_log')
    # ### end Alembic commands ###
