"""add test_variants table

Revision ID: ebe712db9259
Revises: 02a666b693b1
Create Date: 2026-06-21 16:51:06.522241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe712db9259'
down_revision: Union[str, Sequence[str], None] = '02a666b693b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_variants_id'), 'test_variants', ['id'], unique=False)
    op.create_index(op.f('ix_test_variants_status'), 'test_variants', ['status'], unique=False)
    op.create_index(op.f('ix_test_variants_user_id'), 'test_variants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_variants_user_id'), table_name='test_variants')
    op.drop_index(op.f('ix_test_variants_status'), table_name='test_variants')
    op.drop_index(op.f('ix_test_variants_id'), table_name='test_variants')
    op.drop_table('test_variants')
    # ### end Alembic commands ###
